### ISSUE TITLE
Coursetable UI style not aligned.

### ISSUE THREAD

**Issue by jc-hiroto** [NTUCourse-Neo/ncn-frontend#15]
## Scenario
- When more than one course is in the cell of time in the course table, the card will not align in the center of the cell.
![image](https://user-images.githubusercontent.com/38657003/148031322-be47b551-0149-45c3-ba08-9344a3226df5.png)

## Cause
- Unknown

## Fix
- TBD

**Comment by maxchou415** [comment]
街西好強喔

**Comment by jc-hiroto** [comment]
Fixed by @swh00tw in the nextjs migration process!
