### ISSUE TITLE
Filter Modal Bug

### ISSUE THREAD

**Issue by swh00tw** [NTUCourse-Neo/ncn-frontend#64]
**Describe the bug**
Remove mechanism is not the same as insert new selection in Filter Modal.

**To Reproduce**
1. Go to 'Course Searching Page'
2. Open Filter Modal (dept or course type)
3. Add some courses then click save.
4. Open again, remove selected by clicking again, then don't press "save", press "X" or anywhere outside Modal.
5. The selected list should not be changed because we do not press "Save". It should remain the same.

**Expected behavior**
However, it change directly.

**Comment by jc-hiroto** [comment]
Acknowledged.👌

**Comment by swh00tw** [comment]
Just a simple solution currently and I will refactor these filters in the future and try to keep `closeOnOverlayClick`.

**Comment by jc-hiroto** [comment]
resolved in #71
