### ISSUE TITLE
Search result incorrect after altering filter

### ISSUE THREAD

**Issue by dlccyes** [NTUCourse-Neo/ncn-frontend#92]
**Describe the bug**
When the search result is empty, no request is sent after you alter or toggle the filters and press search.

**To Reproduce**
1. Search for some random things to make the search result empty e.g. search "物理" while applying 中文系 filter
2. Alter or toggle the filters but don't change the keyword e.g. untoggle 中文系 filter
3. Press search
4. No request is sent and the search result remains empty

**Expected behavior**
Search result is always correct, regardless of my past behavior.

**Desktop:**
 - OS: MacOS Monterey 12.5
 - Browser: Firefox 91.12.0esr & Chrome 103.0.5060.134

**Comment by swh00tw** [comment]
Thanks for finding this bug for us. Already solved in PR #93 .
