### ISSUE TITLE
Can't see NTU Rating's Post 

### ISSUE THREAD

**Issue by Gting6** [NTUCourse-Neo/ncn-frontend#97]
## Problem
If added `?refererrer` to url, NTU Rating can only get the scores but posts.

## Possible Workaround
In `Panel.js`, line 353 and line 396, modify `?referrer` to `&referrer`

**Comment by jc-hiroto** [comment]
Thanks for reporting this issue and providing a workaround.
We will fix this ASAP. 🙌
